circuits: 10

fast:
 - jumping jacks
 - push ups
 - dead bugs
 - bicycle kicks
 - burpies
 - mountain climbers
 - rowing
 - glute bridge march
 - ball pendulum
 - run in place
 - ball lift transfer
 - sumo squats
 - arm elbows
slow:
 - middle crunches
 - left crunches
 - right crunches
 - live bugs
 - middle plank
 - left plank
 - right plank
 - leg lifts
 - left hip dip
 - right hip dip
 - kicking 
 - leg v lift
 - feet on ground crunch
 - squats
  
