fast:
 - jumping jacks
 - pushups
 - dead bugs
 - bicycle kicks
 - burpies
 - mountain climbers
slow:
 - middle crunches
 - left crunches
 - right crunches
 - live bugs
 - middle plank
 - left plank
 - right plank

  
